"""create classrooms table

Revision ID: 9291d2414f54
Revises: 56fefb4ca1ec
Create Date: 2026-07-09 17:44:43.386264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9291d2414f54'
down_revision: Union[str, Sequence[str], None] = '56fefb4ca1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.Enum('CLASS_3', 'CLASS_4', 'CLASS_5', 'CLASS_6', 'CLASS_7', 'CLASS_8', name='grade'), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'grade', 'section', name='uq_classroom')
    )
    op.create_index(op.f('ix_classrooms_academic_year_id'), 'classrooms', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classrooms_school_id'), 'classrooms', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classrooms_school_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_academic_year_id'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
