"""add phone and email to schools

Revision ID: bb43200cc662
Revises: 9bf370bce0cc
Create Date: 2026-07-09 16:05:38.244717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb43200cc662'
down_revision: Union[str, Sequence[str], None] = '9bf370bce0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('schools', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'email')
    op.drop_column('schools', 'phone')
    # ### end Alembic commands ###
