"""create teacher profiles table

Revision ID: ed526cb84929
Revises: 9291d2414f54
Create Date: 2026-07-09 18:32:50.382096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed526cb84929'
down_revision: Union[str, Sequence[str], None] = '9291d2414f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('designation', sa.Enum('PRINCIPAL', 'VICE_PRINCIPAL', 'COORDINATOR', 'TEACHER', 'ASSISTANT_TEACHER', name='teacherdesignation'), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'employee_id', name='uq_teacher_employee')
    )
    op.create_index(op.f('ix_teacher_profiles_school_id'), 'teacher_profiles', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_user_id'), 'teacher_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_profiles_user_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_school_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    # ### end Alembic commands ###
